### ISSUE TITLE
kpoint mesh for tetrahedron method

### ISSUE THREAD

**Issue by lukeamyers** [PhasesResearchLab/dfttk#54]
For the three step relaxation, we need to ensure the use of a gamma centered mesh for the third "static" step. When using the tetrahedron method (ISMEAR=5), a gamma centered mesh should be used.

https://www.vasp.at/wiki/index.php/ISMEAR

> ISMEAR=−5: tetrahedron method with Blöchl corrections (use a [Γ-centered k-mesh](https://www.vasp.at/wiki/index.php/KPOINTS)).

https://www.smcm.iqfr.csic.es/docs/vasp/node58.html

> Mind: The division scheme (or the generating basis of the k-mesh) must lead to a k-mesh which belongs to the same class of Bravais lattice as the reciprocal unit cell (Brillouin zone). Any symmetry-breaking set-up of the mesh cannot be handled by VASP. Hence such set-ups are not allowed -- if you break this rule an error message will be displayed. Furthermore the symmetrisation of the k-mesh can lead to meshes which can not be divided into tetrahedrons (at least not by the tetrahedron division scheme implemented in VASP) -- if one uses meshes which do not have their origin at $\Gamma$ (for certain lower symmetric types of Bravais lattices or certain non-symmetry conserving shifts). Therefore only very special shifts are allowed. If a shift is selected which can not be handled you get an error message. For reasons of safety it might be a good choice to use only meshes with their origin at $\Gamma$ (switch 'G' or 'g' on third line or odd divisions) if the tetrahedron method is used. 

As it stands any kpoint mesh could be used.

**Comment by lukeamyers** [comment]
This may be useful to change the kpoints during the third step in three step relaxation

http://materialsproject.github.io/custodian/custodian.vasp.utils.html#custodianvasputils-module

custodian.vasp.utils module

Utility methods for VASP error handlers.
custodian.vasp.utils.increase_k_point_density

**Comment by nhew1994** [comment]
I did a quick test with Al - static calculation with ISMEAR = -5 using Gamma and Monkhorst pack. Both gave the same energies and VASP gave no error.

**Comment by nhew1994** [comment]
I posted a question on the VASP forum: https://www.vasp.at/forum/viewtopic.php?t=19663

**Comment by lukeamyers** [comment]
Okay cool thanks. Probably no need to do anything until we actually identify a problem then.

**Comment by nhew1994** [comment]
See the reply from the VASP forum: https://www.vasp.at/forum/viewtopic.php?t=19663 

"Hi,

The tetrahedron method in VASP does work with both the Gamma-centered and Monkhorst-Pack k-meshes. In some cases VASP might be unable to construct a generating k-lattice. To avoid this problem make sure to include the Gamma point in the k-mesh. But if such case is encountered an error should be shown together with suggestions on how to avoid this problem. "

So if don't get a VASP error. It is ok. I will close this issue.
