### ISSUE TITLE
plot_config_energy() can not handle configs with differnce number of atoms.

### ISSUE THREAD

**Issue by lukeamyers** [PhasesResearchLab/dfttk#55]
I would like to compare energy difference per atom. but since the configs have different number of atoms the volume are different even though the volume/atom is the same.

To fix, I think the dataframe should just have columns for molar quantities. and all the calculations should be performed in the extract config_data function. alternatively a new dataframe could be made for the molar quantities.

**Comment by nhew1994** [comment]
Sure, you can just add a column called something like eV/atom and volume/atom maybe. Also, be able to scale this to the number of atoms desired in compare_energy_difference.

**Comment by nhew1994** [comment]
I think this has been resolved?

**Comment by lukeamyers** [comment]
oh, yes.
