### ISSUE TITLE
nameing files with ".1relax", ".2relax", ".3static"  at the end

### ISSUE THREAD

**Issue by lukeamyers** [PhasesResearchLab/dfttk#74]
This seems to be what was causing github to be saying that we have roff files in our code.

We should probably change how we name the output files so that these aren't considered to be extensions I think.

**Comment by nhew1994** [comment]
Is this still an issue?

**Comment by lukeamyers** [comment]
I think it's a little awkward to treat the VASP step as a file extension, since it isn't a different type of file. I would suggest changing the naming to "OUTCAR_3static" instead of "OUTCAR.3static." 

However, this is not a big deal, and if this is the standard way to name the VASP config files with custodian at each step is to add an extension, then there is no problem.

**Comment by nhew1994** [comment]
You can change the suffix to _3static instead of .3static. But then we will have to change all the other names to _3static.
